### ISSUE TITLE
[cli-issue] - When activities logs are outputted as .csv, they look malformed when opened with excel.

### ISSUE THREAD

**Issue by JJ-rivery** [RiveryIO/rivery_cli#16]
** CLI Version **
* 0.3.3

**Describe the bug**
Extracting activity logs as .csv's results in a malformed file in the destination path.

**To Reproduce**
Pull the activity logs of a recent runId as a .csv and examine the structure of the file when you open it in a tool like excel.

```bash
> rivery activities logs fetch --runId 38a0f6a0e0994a319fcdc0b34bb300fc --filePath C:/Users/Ujjwal-Work/Desktop/Rivery/logs/webinar_extracted_logs/test.csv
```
![image](https://user-images.githubusercontent.com/84088149/125126351-f8f7c300-e0c8-11eb-90dc-3c34ce61550e.png)

**Expected behavior**
I want the logs to look like the ones that come out of the UI when one clicks the "download logs" button.

**OS**
Windows 10

** Python Version **
3.8.10

**Additional context**
Need this for webinar. Exporting out as a .txt file, the file looks okay. But the malforming only happens when I try to export it as a .csv that I want to open with excel.

**Comment by giladlevy7** [comment]
Thanks for letting us know JJ!
Solved in 0.3.4.
